---
title: "GDP per capita per Continent"
author: "Manuel Davril"
date: "June 021"
output:
  pdf_document: default
  html_document: default
---

# Load data

```{r load-libraries-data, warning=FALSE, message=FALSE}
library(tidyverse)  # For ggplot, dplyr, and friends
library(gapminder)  # For health/wealth data
library(ggridges)   # For ridge plots
library(gghalves)   # For half geoms
```

## Histograms

```{r filter-gapminder-1997, warning=FALSE, message=FALSE}

data <-
  as.data.frame(gapminder)

data1997 <- data %>%
  filter(year == '1997')

```

```{r plot-histogram, warning=FALSE, message=FALSE}

ggplot(data1997,
       aes(x = gdpPercap,
           fill = continent))+
  geom_histogram(binwidth = .06,
                 color = 'black',
                 boundary = 100)+
  facet_wrap(~continent)+
  guides(fill = FALSE)+
  scale_x_log10() +
  theme_bw()+
  labs(title = "GDP per Capita",
       subtitle = "Year: 1997",
       size = 8,
       x = "",
       y = "")

```

## Densities


```{r plot-ridgeplot, warning=FALSE, message=FALSE}

ggplot(data,
       aes(x = lifeExp,
           y = factor(year),
           fill = continent)) +
  geom_density_ridges(alpha = .3) +
  guides(fill = guide_legend(title = "")) +
  labs(y = NULL) +
  theme(plot.subtitle = element_text(size = 9),
        plot.title = element_text(size = 12)) +
  labs(title = "Life Expectancy through the years",
       subtitle = ('1952 - 2007'),
       x = "") +
  theme_minimal()

```


## Boxes and violins

```{r filter-gapminder-2007-sans-oceania, warning=FALSE, message=FALSE}

data2007 <- data %>%
  filter(year == '2007' & continent != 'Oceania')

ggplot(data2007,
       aes(x = continent,
           y = gdpPercap,
           fill = continent)) +
  geom_half_point(aes(color = continent)) +
  guides(fill = guide_legend(title = ""),
         color = guide_legend(title = "")) +
  geom_half_boxplot()+
  theme(legend.position = "none")+
  labs(title = "GDP Per Capita",
       subtitle = "Year: 2007",
       x = "",
       y = "GDP Per Capita") +
  theme(plot.title = element_text(size = 12)) +
  theme_bw()

```



